### PR TITLE
Feature/select tree

### PR DESCRIPTION
**Pull request by JohnLeeroy**
Moved a bunch of files to be more functional.
Updated the Select Tree Fragment look
Refactored how data was loaded to the fragment.

### CODE REVIEW

**Comment by JohnLeeroy** [comment]
screen shot 2016-12-10 at 4 08 19 pm

**Comment by LondonAtlas** [comment]
round dem edges bra

**Comment by JohnLeeroy** [comment]
I'll look into it

**Review by LondonAtlas — APPROVED** [review]

**Comment by JohnLeeroy** [comment]
screen shot 2016-12-10 at 4 31 45 pm

**Pull request merged**
